//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BusinessCardBook.rc에서 사용되고 있습니다.
//
#define IDD_TAKEINFORM                  5
#define IDD_BUSINESSCARDBOOKFORM        101
#define IDD_FINDINGFORM                 105
#define IDD_TAKEOUTFORM                 107
#define IDC_BUTTON_BUSINESSCARD         1001
#define IDC_BUTTON_PERSONAL             1003
#define IDC_STATIC_PERSONAL_NAME        1004
#define IDC_STATIC_PERSONAL_NAME_TEXT   1005
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER 1006
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER_TEXT 1007
#define IDC_STATIC_PERSONAL_EMAILADDRESS_TEXT 1008
#define IDC_STATIC_PERSONAL_EMAILADDRESS 1009
#define IDC_STATIC_PERSONAL_POSITION    1010
#define IDC_STATIC_PERSONAL_POSITION_TEXT 1011
#define IDC_BUTTON_COMPANY              1012
#define IDC_STATIC_COMPANY_NAME_TEXT    1013
#define IDC_STATIC_COMPANY_ADDRESS      1014
#define IDC_STATIC_COMPANY_ADDRESS_TEXT 1015
#define IDC_STATIC_COMPANY_TELEPHONENUMBER 1016
#define IDC_STATIC_COMPANY_FAXNUMBER    1017
#define IDC_STATIC_COMPANY_TELEPOHNENUMBER_TEXT 1018
#define IDC_STATIC_COMPANY_FAXNUMBER_TEXT 1019
#define IDC_STATIC_COMPANY_HOMEPAGE     1020
#define IDC_STATIC_COMPANY_HOMEPAGE_TEXT 1021
#define IDC_BUTTON_FIRST                1022
#define IDC_BUTTON_PREVIOUS             1023
#define IDC_BUTTON_NEXT                 1024
#define IDC_BUTTON_LAST                 1025
#define IDC_BUTTON_TAKEIN               1026
#define IDC_BUTTON_TAKEOUT              1027
#define IDC_BUTTON_FIND                 1028
#define IDC_BUTTON_ARRANGE              1029
#define IDC_STATIC_COMPANY_NAME         1030
#define IDC_COMBO_PERSONAL_EMAILADDRESS 1031
#define IDC_STATIC_PERSONAL_AT          1032
#define IDC_COMBO_PERSONAL_POSITION     1033
#define IDC_BUTTON_CONDITION            1035
#define IDC_EDIT_CONDITION_NAME         1037
#define IDC_BUTTON_SELECT               1044
#define IDC_EDIT_PERSONAL_NAME          1045
#define IDC_EDIT_PERSONAL_TELEPHONENUMBER 1046
#define IDC_EDIT_PERSONAL_EMAILADDRESS  1047
#define IDC_EDIT_COMPANY_NAME           1048
#define IDC_EDIT_COMPANY_ADDRESS        1049
#define IDC_EDIT_COMPANY_TELEPHONENUMBER 1050
#define IDC_EDIT_COMPANY_FAXNUMBER      1051
#define IDC_EDIT_COMPANY_HOMEPAGE       1052
#define IDC_EDIT_COMPANY_URL            1052
#define IDC_STATIC_COMPANY_TELEPHONENUMBER_TEXT 1053
#define IDC_STATIC_COMPANY_URL          1054
#define IDC_STATIC_COMPANY_URL_TEXT     1055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
